# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageDownloader' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImageDownloader
  pod 'Masonry'
  pod 'SSZipArchive'
  pod 'Realm'

  target 'ImageDownloaderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ImageDownloaderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
